- name: Install packages utils
  hosts: webserver
  tasks:
    - name: Upgrade all packages
      become: true
      yum:
        name: '*'
        state: latest

    - name: Instalando Pacotes
      become: true
      yum:
        name:
          - nmap
          - telnet
          - htop
          - vim
          - glibc-utils
          - git
          - curl
          - bind-utils
          - httpd
        state: latest
        register: resultado
        update_cache: yes
        
    - name: Exibir resultado
      debug:
        msg: "{{ resultado }}"
