---
- hosts: all
  gather_facts: False

  tasks:
    - name: Obtendo data do Sistema
      shell: "date -u"
      register: linux_date

    - name: Exibindo a data
      debug:
        msg: "Data do sistema e': {{ linux_date }}"
